# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_thr <- function(input, lambda, pos, sp_locs) {
    .Call(`_ssJIVE_soft_thr`, input, lambda, pos, sp_locs)
}

sfpca_bic <- function(x, K, Omegv, sp_locsv, lamvs, alphavs) {
    .Call(`_ssJIVE_sfpca_bic`, x, K, Omegv, sp_locsv, lamvs, alphavs)
}

